create table public.staf
(
    id    integer generated by default as identity,
    name  varchar not null,
    role  varchar not null,
    money integer not null
);

INSERT INTO staf VALUES (DEFAULT,'Саня','уборщик',10000);
INSERT INTO staf VALUES (DEFAULT,'Петя','директор',200000);
INSERT INTO staf VALUES (DEFAULT,'Зина','секретарь',50000);
INSERT INTO staf VALUES (DEFAULT,'Вася','программист',120000);

--READ COMMITTED
--Фантомы
--ШАГ 1)
START TRANSACTION ISOLATION LEVEL READ COMMITTED;
--ШАГ 4)
INSERT INTO staf VALUES (DEFAULT,'Сергей','консультант',70000);
--ШАГ 5)
COMMIT;

--REPEATABLE READ
--Фантомы
--ШАГ 1)
START TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--ШАГ 4)
INSERT INTO staf VALUES (DEFAULT,'Сергей2','консультант',70000);
--ШАГ 5)
COMMIT;


--REPEATABLE READ
--Аномалии сериализации
--ШАГ 1)
SELECT * FROM staf;
--ШАГ 2)
START TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--ШАГ 4)
UPDATE staf SET money = money-10000 WHERE id=2;
SELECT * FROM staf;
--ШАГ 6)
COMMIT;



--SERIALIZABLE
--Аномалии сериализации
--ШАГ 1)
SELECT * FROM staf;
--ШАГ 2)
START TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--ШАГ 4)
UPDATE staf SET money = money-10000 WHERE id=2;
SELECT * FROM staf;
--ШАГ 6)
COMMIT;

--РЕАЛИЗАЦИЯ ТОЧКИ СОХРАНЕНИЯ

SELECT * FROM staf;

START TRANSACTION ISOLATION LEVEL READ COMMITTED;

SAVEPOINT point;

INSERT INTO staf VALUES (DEFAULT,'иван','бдшник',70000);

SELECT * FROM staf;

ROLLBACK TO SAVEPOINT point;

SELECT * FROM staf;

RELEASE SAVEPOINT point;

COMMIT;

DROP TABLE staf;